apiVersion: apps/v1
kind: Deployment
metadata:
  name: lxcfs-webhook
  namespace: lxcfs
  labels:
    app: lxcfs-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lxcfs-webhook
  template:
    metadata:
      labels:
        app: lxcfs-webhook
    spec:
      containers:
        - name: lxcfs-webhook
          image: dev-deploy.deepexi.com/2048-component/lxcfs/lxcfs-admission-webhook:v1
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      imagePullSecrets:
        - name: lxcfs
      volumes:
        - name: webhook-certs
          secret:
            secretName: lxcfs-webhook
