apiVersion: v1
kind: Service
metadata:
  name: lxcfs-webhook
  namespace: lxcfs
  labels:
    app: lxcfs-admission-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: lxcfs-webhook
