apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-lxcfs-admission-webhook-cfg
  namespace: lxcfs
  labels:
    app: lxcfs-webhook
webhooks:
  - name: lxcfs-webhook.deepexi.com
    clientConfig:
      service:
        name: lxcfs-webhook
        namespace: lxcfs
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["pod", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
#    namespaceSelector:
#      matchLabels:
#        lxcfs-admission-webhook: enabled
